name: "PBRP Build Action"
author: 'mlm-games'
description: "A GitHub action to build PitchBlack Recovery Project (PBRP) for a specified device."

inputs:
  MANIFEST_BRANCH:
    description: 'PBRP Manifest Branch'
    default: 'android-12.1'
    type: string
  DEVICE_TREE:
    description: 'Custom Recovery Tree URL (your device tree repository)'
    default: "https://github.com/${{ github.repository }}"
    type: string
   DEVICE_TREE_BRANCH:
    description: 'Custom Recovery Tree Branch (leave blank to use the default branch of the repository)'
    default: ''
    type: string
  DEVICE_NAME:
    description: 'Specify your Device Codename (leave blank to auto-detect)'
    default: ''
    type: string
  DEVICE_PATH:
    description: 'Specify your Device Path (leave blank to auto-detect)'
    default: ''
    type: string
  MAKEFILE_NAME:
    description: 'Specify your Makefile Name (leave blank to auto-detect)'
    default: ''
    type: string
  BUILD_TARGET:
    description: 'Specify your Build Target (use "pbrp" for Android 11 or above)'
    default: 'recovery'
    type: choice
    options:
      - pbrp
      - boot
      - recovery
      - vendorboot

runs:
  using: 'composite'
  steps:
    - name: Set up environment variables
      shell: bash
      run: |
        echo "MANIFEST_BRANCH=${{ inputs.MANIFEST_BRANCH }}" >> $GITHUB_ENV
        echo "DEVICE_TREE=${{ inputs.DEVICE_TREE }}" >> $GITHUB_ENV
        echo "DEVICE_TREE_BRANCH=${{ inputs.DEVICE_TREE_BRANCH }}" >> $GITHUB_ENV
        echo "DEVICE_NAME=${{ inputs.DEVICE_NAME }}" >> $GITHUB_ENV
        echo "DEVICE_PATH=${{ inputs.DEVICE_PATH }}" >> $GITHUB_ENV
        echo "MAKEFILE_NAME=${{ inputs.MAKEFILE_NAME }}" >> $GITHUB_ENV
        echo "BUILD_TARGET=${{ inputs.BUILD_TARGET }}" >> $GITHUB_ENV

    - name: 'Build PBRP'
      shell: bash
      run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh

branding:
  icon: "terminal"
  color: "blue"
